# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk17

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту for.viy@gmail.com усли сборка упала
notifications:
  email:
    recipients:
      -for.viy@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="c17e9a0d-8887-4a0d-81cd-ffaeb8c17bbe"
